### ISSUE TITLE
"Enterprise Data Inventory & Public Data Listing" as one evaluated category. 

### ISSUE THREAD

**Issue by rebeccawilliams** [project-open-data/project-open-data-dashboard#106]
[EDI metric updates](https://github.com/GSA/project-open-data-dashboard/issues/96), these may already be addressed: 

*Rename "Is the EDI available on Data.gov?" Field to reflect when there are no redactions/everything is available via the PDL.
- Think we should add something for # of datasets with redactions, and % of redacted datasets with explanations in "rights" metadata field?

Notes from @philipashlock:

> In talking with Jamie we decided:
> - We'll keep the EDI tab separate from PDL regardless of how EDI is submitted, but we can rename the last EDI field from "Is the EDI available on Data.gov?" to "PDL includes non-public datasets and no redactions"
> - The non-public dataset change metrics would display under EDI
> - We'll keep the accessLevel fields just under the EDI tab

**Comment by rebeccawilliams** [comment]
See #119.

**Comment by rebeccawilliams** [comment]
I renamed this issue to reflect the broader issue that EDIs and PDLs are often one and the same.

**Comment by philipashlock** [comment]
@CEhmann You referenced this from the #135 by saying to add a new field labeled “Agency provides a public Enterprise Data Inventory on data.gov” but it seems like that would be contradicting the change we already made here. 

Previously the field was labeled "Is the EDI available on Data.gov?" which is essentially what you're asking for now, but Rebecca thought it would be less confusing to instead label it as "PDL includes non-public datasets and no redactions" which is what we're currently using on the site. 

Just to confirm, you're ok with essentially reverting back to what it was originally, albeit with slightly different wording, correct?

**Comment by justgrimes** [comment]
@philipashlock Yes, then we are advocating for this to be reverted back. The question "PDL have non-public data assets w/ no redactions" is not the same as "EDI listed as a data asset within the PDL".  There still seems to be some general confusion around how to handle EDI/PDL reporting; separating out and refining the questions on the dashboard will help to address this issue.

**Comment by rebeccawilliams** [comment]
Closing previous feature requests to focus on simplification and automation.
