### ISSUE TITLE
[pod v1.1] programCode and bureauCode does not validate when empty

### ISSUE THREAD

**Issue by rhabbachi** [project-open-data/project-open-data-dashboard#110]
Looking at the [Project Open Data Metadata Schema v1.1](https://project-open-data.cio.gov/v1.1/schema/), the fields [programCode](https://project-open-data.cio.gov/v1.1/schema/#programCode) and [bureauCode](https://project-open-data.cio.gov/v1.1/schema/#bureauCode) are required but have Cardinality (0,n). My interpretation is that the field array should be there but can be empty. We are working on validating the data.json for one of our clients but it fails on http://labs.data.gov/dashboard/validate for those two fields when empty.

Is my interpretation about the required field with empty values correct? Am I missing something?

**Comment by rebeccawilliams** [comment]
Hi @rhabbachi - I am not sure if I understand your question. There should be a `programCode` and `bureauCode` for all datasets, which is required. If this is not included it should fail. 

Have you seen: https://project-open-data.cio.gov/v1.1/schema/#bureauCode

cc @philipashlock

**Comment by rhabbachi** [comment]
@rebeccawilliams Yes you are right. Sorry I kinda miss understood the Schema specs.
