### ISSUE TITLE
Viewing the customers side- how many downloaded the databases?

### ISSUE THREAD

**Issue by shayliraz** [project-open-data/project-open-data-dashboard#112]
Hi there,
I think it would be both important and interesting to be able to view the level of usage of the data uploaded. that would give us a sense for the effectiveness of the project (and the differences between the offices relevance and attractiveness of the metadata).

Is that something do-able?

Thanks,
Shay

**Comment by shayliraz** [comment]
Anyone???

**Comment by rebeccawilliams** [comment]
@shayliraz The Project Open Data Dashboard simply analyzes CFO-Act agencies' data.json metadata files as is required by OMB M-13-13. This team does not have access to agency download information and does not 'upload' any data. 

Agencies are beginning to implement web analytics (via the Digital Analytics Program) across their web properties, which can assess downloads and web traffic, etc. You may be interested in these two relevant projects:
* https://pulse.cio.gov/ (tracks web anaytics on agency home pages) Open source at: https://github.com/18f/pulse/issues
* https://analytics.usa.gov/ (tracks files accessed with 'top downloads' -- it's worth noting that API use is not included in that assessment) Open source at: https://github.com/18F/analytics.usa.gov/issues
