### ISSUE TITLE
Symbols not displaying in dashboard in Internet Explorer 11

### ISSUE THREAD

**Issue by justgrimes** [project-open-data/project-open-data-dashboard#113]
Symbols not displaying in dashboard in Internet Explorer 11 (v 11.0.9600.18036)

![image](https://cloud.githubusercontent.com/assets/781944/10769271/93907c9a-7cbb-11e5-8240-1881e63a68d1.png)

**Comment by rebeccawilliams** [comment]
@justgrimes see #70

**Comment by justgrimes** [comment]
This is the same problem as mentioned in #70; There is a security setting in IE that is preventing fonts from being downloaded. If you are a user having this problem either add this site as a trusted site or Go in to Options > Security > Internet zone, Downloads > Font Download is set to Enable.
