### ISSUE TITLE
Link Validator: ESRI Services coming up as status 405

### ISSUE THREAD

**Issue by bbrotsos** [project-open-data/project-open-data-dashboard#115]
Any ESRI service is coming back with status 405 on project open data validator when I’m getting 200 on curl.  For example from the link validator output, this dataset shows 405

ID | Title | URL | http_status
--- | --- | --- | ---    
USDA-FS-00033 | FS National Forest Dataset (US Forest Service Proclaimed Forests) | http://apps.fs.usda.gov/ArcX/rest/services/EDW/EDW_ProclaimedForestBoundaries_01/MapServer | 405

But running curl
```
$ curl -s -D - http://apps.fs.usda.gov/ArcX/rest/services/EDW/EDW_ProclaimedForestBoundaries_01/MapServer 
HTTP/1.1 200 OK
```

**Comment by philipashlock** [comment]
Looks like this is a bug on the Esri side which has apparently already been reported by EPA and ticketed as ENH-000092414. We've seen similar bugs from other servers and are trying to track them and find workarounds in #116

**Comment by bbrotsos** [comment]
Thanks,  I was able to reproduce the error with doing a head request.  I

```
curl http://gis.ers.usda.gov/arcgis/rest/services/ --head
HTTP/1.1 405 Method Not Allowed
```

**Comment by ecaldwell** [comment]
Have you tried appending `?f=json` to the end of the service url? I get `200 OK` as long as I include that in the `HEAD` request.
