### ISSUE TITLE
Remove % Valid and Dataset # from the homepage

### ISSUE THREAD

**Issue by rebeccawilliams** [project-open-data/project-open-data-dashboard#121]
We've heard the % column seems like a grade that doesn't line up with the evaluation columns and want to prevent confusion. Also, this was more relevant when many agencies didn't have valid data.json, which is now thankfully, much less of an issue. 

These should still be included at the Agency level.

**Comment by philipashlock** [comment]
I think we'll create a separate page that just shows the automated metrics and remove the automated metrics (two columns on the right) from the main table.

**Comment by rebeccawilliams** [comment]
Closing previous feature requests to focus on simplification and automation.
