### ISSUE TITLE
Reconcile EDI and PDL

### ISSUE THREAD

**Issue by rebeccawilliams** [project-open-data/project-open-data-dashboard#125]
These should be one tab (as an interim before the redesign) OR these should repeats should only be on one tab: 

EDI / PDL 
- Bureaus represented **%**
- Programs represented **%**
- PDL includes non-public datasets and no redactions **AUTOMATE**
- Percentage growth in records since last quarter
  - Access Level = Public 
  - Access Level = Restricted
  - Access Level = Non-Public
- Number of Datasets
  - Access Level = Public 
  - Access Level = Restricted
  - Access Level = Non-Public
  - Number of Public Datasets with File Downloads 
- Number of APIs
  - Access Level = Public 
  - Access Level = Restricted
  - Access Level = Non-Public
- Number of Collections
  - Access Level = Public 
  - Access Level = Restricted
  - Access Level = Non-Public
- Total number of access and download links
  - Quality Check: Accessible links
  - Quality Check: Redirected links
  - Quality Check: Error links
  - Quality Check: Broken links
- License Specified 
  etc

Remove the following:
- Inventory > Public listing
- Spot Check? <---- I think we don't need to collect this every quarter, what do others think?
- Quality Check: Links are sufficiently working
- Valid Metadata  
- /data 
-  /data.json  
- Harvested by data.gov  
- Views on data.gov for the quarter
  etc

**Comment by philipashlock** [comment]
This looks like a duplicate of #106

**Comment by rebeccawilliams** [comment]
This can be closed to focus on simplification and automation.
