### ISSUE TITLE
backend request: provide only 1 update button, rather than 2

### ISSUE THREAD

**Issue by rebeccawilliams** [project-open-data/project-open-data-dashboard#126]
Currently there are 2 Update buttons: the top larger button updates the Review status, while the smaller button below updates everything else.  See the red boxes:

![update](https://cloud.githubusercontent.com/assets/1725454/12240829/9dfc5842-b85d-11e5-8043-c2ce4b1a0ffa.png)

Having 2 buttons has led to OMB staff clicking the incorrect button and losing evaluation work. It would be great if there was 1 update button that updated everything on the agency page.

**Comment by qusai919** [comment]
can i know which backend programming language are you using?

**Comment by thisisrai** [comment]
Has this issue been resolved?

**Comment by rebeccawilliams** [comment]
This can be closed to focus on simplification and automation.
