### ISSUE TITLE
No crawls since December 7th 

### ISSUE THREAD

**Issue by klever4ever** [project-open-data/project-open-data-dashboard#133]
It appears that no crawls have occurred since December 7th for Milestone 10.

**Comment by kvuppala** [comment]
@klever4ever thank you for the flag, we are looking into it.

**Comment by philipashlock** [comment]
Thanks for flagging. The cron job has been reconfigured and a full run has been conducted, but we're investigating the issue and looking at why this wasn't caught earlier. In any case, the crawls have been refreshed and we'll be monitoring to make sure they continue to run on schedule.
