### ISSUE TITLE
Getting PHP error when running the app

### ISSUE THREAD

**Issue by ColinMaudry** [project-open-data/project-open-data-dashboard#139]
I have followed the following steps to set up the environment on my server:

https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-ubuntu-12-04 (although my server runs Ubuntu 15.10)

Then I have followed the instructions in the README.

I have run `composer install` but all dependencies came from the Git repo.

But I get an error that you can see at http://e-procurement.donnéesouvertes.fr/ or in the screenshot below:

![error](https://cloud.githubusercontent.com/assets/3747136/14983781/8b94e3d2-113f-11e6-8e14-1935c93c2bcf.png)

I have set the whole app code to `777` to be sure permissions are not a problem:

```bash
chmod -R 777 *
```

I don't know what gearman.php can be, or where `core/Common.php` is located. Shall I install Gearman PHP wrapper? http://pecl.php.net/package/gearman

PS: our objective is to use your code as a basis to develop a dashboard that tracks the progress of public contracting data opening in France.

**Comment by philipashlock** [comment]
You should be able to just rename the file in /application/config/ from `gearman.php.sample` to `gearman.php` like the other sample config files. Does that fix it?

At this point, most of the code that's readily reusable would be if you're working with [data.json](https://project-open-data.cio.gov/v1.1/schema/) files and doing automated analysis on them. Is there something similar to the data.json files with catalogs of metadata being used for the public contracting data?

**Comment by alex-perfilov-reisys** [comment]
for `core/Common.php`, there is a fix
https://github.com/bcit-ci/CodeIgniter/commit/69b02d0f0bc46e914bed1604cfbd9bf74286b2e3

**Comment by ColinMaudry** [comment]
@philipashlock Thanks, I think your solution worked, since I get an new error message:

```
Unable to select the specified database: pod_database
```
My guess is that I still have to configure the database to be used.  `pod_database` is probably the default database name.

Above all, I think I hadn't understood in what extent I needed to configure and reproduce the way of working at https://labs.data.gov/dashboard/offices. I expected less configuration to get the "empty shell" (no data) to display some UI.
