### ISSUE TITLE
How accurate are dashboard data set count?

### ISSUE THREAD

**Issue by DamonDavis** [project-open-data/project-open-data-dashboard#15]
HealthData.gov currently reports 1570 datasets.  The dashboard shows over 1600.  Where is the 1600 coming from and how often is the dashboard upated?

**Comment by rebeccawilliams** [comment]
Hi @DamonDavis. The dataset count comes from www.hhs.gov/data.json which you are redirecting from healthdata.gov, so those numbers should be consistent. 

The dashboard updates the number on a nightly basis and takes a snapshot of the number of datasets at the end of each quarter. 

Hope that helps!
