### ISSUE TITLE
Running broken link report by a Agency

### ISSUE THREAD

**Issue by bbrotsos** [project-open-data/project-open-data-dashboard#154]
Does the CLI expose a call to run report on Agency broken URLs in the data.json file?  This is the same full CSV error log download file that is located on agency page with URL errors.

**Comment by rebeccawilliams** [comment]
+1 to this question

**Comment by bbrotsos** [comment]
The crawler is daily, but it was not logging USDA because www.usda.gov/data.json was giving 503 errors on HTTP HEAD calls.  Working to fix on USDA end.
