### ISSUE TITLE
Harvesting from HealthData.gov

### ISSUE THREAD

**Issue by DamonDavis** [project-open-data/project-open-data-dashboard#16]
for HHS,there's an X for "harvesting" on the dashboard.  Why? most of the content in the health domain comes from healthdata.gov, so i'm confused.

**Comment by rebeccawilliams** [comment]
@DamonDavis Hi Damon, I think this was referencing whether or not hhs.gov/data.json was being harvested to Data.gov. I assume it is moot now, let me know if you need additional clarity.
