### ISSUE TITLE
Feature request: email notifications

### ISSUE THREAD

**Issue by dsmorgan77** [project-open-data/project-open-data-dashboard#64]
It would be great to receive a notification when OMB updates information for my agency on this dashboard.

**Comment by rebeccawilliams** [comment]
@dsmorgan77 Would you like emails when evaluations are complete? What types of emails would be helpful?

**Comment by rebeccawilliams** [comment]
@dsmorgan77 We are addressing the home page confusion with #123 and OMB Staff will email POCs upon completion to set up follow up phone calls. I am going to close this issue for now, because I think automating this issue is not a priority when we have a relatively low lift manual process in place.
