### ISSUE TITLE
add "Number of APIs" explanation to the documentation

### ISSUE THREAD

**Issue by rebeccawilliams** [project-open-data/project-open-data-dashboard#89]
Included in the PDL automated metrics, needs updated information linked to the `i` symbol: 
![screen shot 2015-03-19 at 11 09 36 am](https://cloud.githubusercontent.com/assets/1725454/6733399/660983da-ce28-11e4-8d58-79a0a0249190.png)
from the documentation page at: http://labs.data.gov/dashboard/docs#pdl_apis

**Comment by nsinai** [comment]
+1!

**Comment by rebeccawilliams** [comment]
Added with #130

**Comment by rebeccawilliams** [comment]
Reopening this until #130 is merged.

**Comment by rebeccawilliams** [comment]
This can be closed to focus on simplification and automation.
