### ISSUE TITLE
add quick link to resolved data.json on main dashboard page 

### ISSUE THREAD

**Issue by rebeccawilliams** [project-open-data/project-open-data-dashboard#92]
Currently you have to click into a department to get to the resolved data.json. It'd be great to have these links more readily available. 

2 places where this link go are:
- Below the Department name or
- Below the Valid medadata percentage

**Comment by philipashlock** [comment]
Can you explain why you think it would useful there? I'm struggling to think of a use case where this would be appropriate there.

**Comment by rebeccawilliams** [comment]
The use case would be for when I want to look at data.json quickly for review or point others to do the same. Another example: https://github.com/18F/API-All-the-X/issues/186#issuecomment-106567065

**Comment by harrisj** [comment]
Hello all. I was playing around with the data.json files before I realized the work you all were doing here.

I think one other issue here is that sometimes agencies *cough* NREL *cough* also have posted in their own specific format rather than the standardized data.json layout. A normalized local version might be even cooler.

**Comment by rebeccawilliams** [comment]
@harrisj and @gbinal, do have additional API metrics/reports that would be helpful? # of APIs with `describedBy` and `describedByType`?  Add them as new issues cc @justgrimes.

To reiterate this issue is asking for a means to quickly get to agency JSON files without having to click through tabs.

**Comment by harrisj** [comment]
I have no such recent analysis of data.json files, but I could circle back and see what I can find. To be honest, I had a lot of issues with even retrieving data.json from some agencies.

**Comment by rebeccawilliams** [comment]
See also #119.

**Comment by rebeccawilliams** [comment]
Some gov-wide metrics are currently available at quaterly / full, e.g. http://labs.data.gov/dashboard/offices/2015-08-31/full

This needs to be documented more clearly.

**Comment by rebeccawilliams** [comment]
This can be closed to focus on simplification and automation.
