### ISSUE TITLE
Unable to convert JSON Schema 1.0 to 1.1 using Chrome

### ISSUE THREAD

**Issue by gatesld** [project-open-data/project-open-data-dashboard#93]
Chrome version 41.0.2272.101 m
When attempting to convert, the browser page becomes blank, after refrehing the screen the previous screen appears to choose the file desired for conversion.

**Comment by rebeccawilliams** [comment]
@gatesld Sorry for the delay in reply. Did this work after waiting and refreshing the tool?

**Comment by rebeccawilliams** [comment]
Closing this, feel free to re-open if you continue have issues.

**Comment by philipashlock** [comment]
@gatesld I can't recreate the issue, but let us know if this issue still seems to exist
