### ISSUE TITLE
Can't pull list of NPS datasets using Data.json Export API

### ISSUE THREAD

**Issue by OpenGlobe** [project-open-data/project-open-data-dashboard#97]
Hi All - 

Having difficulties pulling a full list of uploaded datasets in either CSV or JSON for National Park Service (nps-gov) records.  Seems to work fine for other agencies, but we're only getting two results when running the following query:

http://labs.data.gov/dashboard/datagov/convert?orgs=nps-gov

Any suggestions?  When checking the NPS org ID it seems 'nps-gov' is correct for the ~1400 records uploaded.

Thanks!

Chris

**Comment by JJediny** [comment]
The URL seems to work now, please feel free to re-open if this issue is still relevant

**Comment by philipashlock** [comment]
Also note that this export feature still uses the deprecated v1.0 schema
